src/main/java/eu/decentsoftware/holograms/api/utils/items/ItemWrapper.java

The ItemWrapper has some duplicate code (12 lines in total) that can be extracted into a small convenience method to use.
This PR does exactly that.

Put duplicate code into convenience method for ItemWrapper

---

src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/ConverterCommon.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/ConvertorType.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/GHoloConverter.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/HolographicDisplaysConvertor.java

Adds [`GHolo`](https://www.spigotmc.org/resources/70913/) as a possible convertion option to `/dh convert`
Changes:
- Moved common code for Hologram creation to a new class called `ConverterCommon` (Static class returning an integer.
- Added null-check for ConverterType to make sure the Converter actually exists.
- Fixed/Prevented a possible exception for the "Hologram already exists" message. It had a `%s` but no replacement value.
- Improved readability of other messages.
On another note: Not a big fan of how I implemented the possible gradient conversion (Actually, from my tests of GHolo does that pattern not even work?), so if you have a better way of converting this, let me know.
I also didn't bother trying to also convert the animations (Mainly because HD Converter also doesn't have …

Add GHolo Converter

---

src/main/java/eu/decentsoftware/holograms/api/utils/location/LocationUtils.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/GHoloConverter.java

The issue was, that the path missed the `H.` part at the start.
Also, GHolo's latest release now uses UUIDs instead of world names, but to still support both did I make a `getWorld` method in the LocationUtils class which will try to create a UUID from the String and if it fails, go back to getting the world by name instead.
I made some tests and the command worked flawlessly for me... Well... The holograms where a bit further down than what the GHolo ones are, but conversion works!

Fix GHolo convertion

---

src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java

Whenever using /dh pages help, you would run into an NPE.
Fixes this issue:
[https://paste.gg/p/anonymous/54301156d9e54de6b67d0a6f933703fd](https://paste.gg/p/anonymous/54301156d9e54de6b67d0a6f933703fd)
This is fixed via using the correct subCommand name. Previously it was "page," which does not correlate to BaseCommand name "pages."

Fixed NPE when using /dh pages help

---

src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java

To be honest: I don't think this is a proper solution to fix this...
But this would (hopefully) prevent a NPE for the `show(Player...)` method in the `HologramLine` class by essentially skipping null player entries.
I feel like it should be looked into preventing the creation of null Player instances to begin with...

Fix(?) possible NPE for show(Player...)

---

src/main/java/eu/decentsoftware/holograms/api/utils/file/FileUtils.java
src/main/java/eu/decentsoftware/holograms/api/utils/location/LocationUtils.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/CMIConverter.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/GHoloConverter.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/HolographicDisplaysConvertor.java

This PR improves the way locations are parsed.
Instead of printing the exception, which may break stuff such as converters (See [this message](https://discord.com/channels/850844430830534696/899603466270441492/941719166396813382) on Discord for further details) will the LocationUtils class now simply catch the exception, print a warning with the exception message/reason and return null.
This allows the converters, which also have a null check now to skip those holograms, to continue working without major issues.
(Also has a minor change for the FileUtils regarding folder creation... Just to reduce IDE warns)

Improve handling of null/invalid locations in Hologram converters

---

src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java

Tab-completing coordinates in the `/dh move` command while the target hologram doesn't exist, prints an error in the console.
See [this message](https://discord.com/channels/850844430830534696/899603466270441492/941723670840229889) on Discord for full context.
This PR fixes it, by making the location null, if the hologram is, followed by checking the location to not be null to apply the coordinates.

Fix Hologram error for non-existant holograms

---

src/main/java/eu/decentsoftware/holograms/api/DHAPI.java
src/main/java/eu/decentsoftware/holograms/api/holograms/Hologram.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java

When using `/dh page insert <hologram> <page> <content>` does DH throw an IllegalArgumentException, if the value is 1.
The issue is, that DH is removing 1 integer value **twice** when using the command: Once on command handling and once in the `insertPage` method when `pages.stream().skip(int)` is used.
The PR fixes this in the following ways:
- Removes the `- 1` from the command handling to instead pass the provided integer value.
- Change `index < 0` to `index < 1` to support the above changes. This could break existing DHAPI usages, but considering that as of now, any usage of `0` would lead to the exact same result is this debatable.

Fix IllegalArgumentException for insert command

---

src/main/java/eu/decentsoftware/holograms/api/DHAPI.java
src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java

This PR (finally!) adds overloads for all the `add`, `set` and `insert` methods of the `DHAPI` to allow the direct usage of ItemStacks and Materials as lines.
Before you had to do a workaround with `"#ICON:" + HologramItem.fromItemStack(ItemStack).getContent()` to achieve the same result.
The new methods basically do this for you now.
I was considering to also add a `setLines` option for ItemStack and Material by having a more generic method accepting `List<Object>` as argument and then have some `instanceof` checks for it, but I decided against it because of conflicts due to the new method having the same erasure as the already existing one...
I could change the existing one a bit to use Object lists, but not sure if that wouldn't be a breaking change for end users...
Either way, I hope …

Add overloads for ItemStack and Material to DHAPI

---

src/main/java/eu/decentsoftware/holograms/api/commands/DecentCommand.java
src/main/java/eu/decentsoftware/holograms/api/commands/TabCompleteHandler.java
src/main/java/eu/decentsoftware/holograms/api/utils/entity/DecentEntityType.java
src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/FeatureSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java

This PR improves the Tab completion for `/dh l ...` subcommands.
Most notably are the following changes:
- Fixed weird checks and lookup for `add` subcommand. (I mentioned this on the Discord server)
- `add`, `set` and `insert` will now suggest the following values:
- `#ICON:`, `#HEAD`, `#SMALLHEAD` or `#ENTITY` when length of content is 1 and provided text partially matches one of these types.
- `(<player_name>)` (`<player_name>` being name of the online players) when content length is 3 and 2nd word is containing `HEAD` or `SKULL`.
- `(%player_name%)` under the above conditions and while PlaceholderAPI is enabled.
- `(HEADDATABASE_<id>)` (`<id>` is literal) under the above conditions and while HeadDatabase is enabled.
- `!ENCHANTED` when the content length is at least 3 words, first …

Improve tab completion for Line Sub commands

---

src/main/java/eu/decentsoftware/holograms/api/holograms/Hologram.java
src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java

This fixes a long standing issue where placeholders got updated every tick rather than every `update-interval`.
The reason behind this is as simple as it is stupid: The `tick()` method in the hologram is only calling the `updateAll()` method when the update interval is reached, which would be fine... However! The tick method also calls `updateAnimationsAll()` and does so every tick interval (which is every tick in this case). This method calls a bunch of other methods which in the end calls a `getText` method. This one in question is also parsing placeholders if text is either null or the `update` boolean is true (which it always was)
So... I now changed the methods a bit to pass a boolean to the `getText` method, so that it won't always update.
For backwards compatibility did I add the …

Fix update interval being ignored

---

src/main/java/eu/decentsoftware/holograms/api/convertor/IConvertor.java
src/main/java/eu/decentsoftware/holograms/api/utils/color/IridiumColorAPI.java

Should fix an issue where `createGradient` in the IridiumColorAPI throws an `ArithmeticException` with reason `/ by zero` (divide by zero) when the `step` value is 1.
The method now returns a `ChatColor` array filled with `WHITE` whenever the step value is one or less. This hopefully fixes other issues that may appear (i.e. negative int used in a for loop).
The exception in detail (Provided by Santtiago on Discord):
https://pastebin.com/y460dQEW

Fix "Divide by Zero" exception in createGradient

---

src/main/java/eu/decentsoftware/holograms/api/convertor/IConvertor.java
src/main/java/eu/decentsoftware/holograms/api/convertor/IConvertorRest.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/CMIConverter.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/ConvertorRest.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/GHoloConverter.java
src/main/java/eu/decentsoftware/holograms/plugin/convertors/HolographicDisplaysConvertor.java

Added sending information to the player after successful conversion of the holograms. It is useful because without it you don't know if the conversion was successful :)
The `convert()` methods in converters now return a new `ConvertorRest` class containing the success of the action (boolean) and the number of holograms converted (methods `getSuccess()` and `getCount()`). This allows the plugin to send the above mentioned success message.

Send success information to player after conversion

---

src/main/java/eu/decentsoftware/holograms/api/DecentHolograms.java
src/main/java/eu/decentsoftware/holograms/api/holograms/DisableCause.java
src/main/java/eu/decentsoftware/holograms/api/holograms/objects/HologramObject.java
src/main/java/eu/decentsoftware/holograms/api/world/WorldListener.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java

Adds some very basic functionality to unload holograms in a world that has been unloaded, or load those in a world that has been loaded again.
Didn't bother adding any complex mechanic behind this.
Maybe consider an API feature in the future to set what type of enable/disable this was to determine what holograms should be loaded (I.e. those unloaded through commands stay unloaded while does done through automation load again)?

Add functionality to (un)load holograms on World (un)load

---

src/main/java/eu/decentsoftware/holograms/api/nms/PacketHandler__ProtocolLib.java

This should hopefully fix the issue of Attacks being ignored/cancelled for entities not handled by DecentHolograms.
Further info can be obtained here: https://github.com/dmulloy2/ProtocolLib/issues/1846
The fix was suggested by derklare in this comment: https://github.com/dmulloy2/ProtocolLib/issues/1846#issuecomment-1214964359

Fix ProtocolLib issue

---

src/main/java/eu/decentsoftware/holograms/api/DHAPI.java

If `lines` is empty, the method will remove all lines of the page

Allow empty lines on setHologramLines

---

src/main/java/eu/decentsoftware/holograms/api/holograms/HologramManager.java

This commit will fix a potential exploit where a player can interact with a hologram by sending an interaction packet at any distance.

Ignore clicks from players far from hologram

---

src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java

Removing the `playerOnly` annotation from the line add sub command, as it doesn't need to be player only. The code already checks the type of the sender when it needs to.
All the other similar commands - insert, delete etc - work from console.

Make line add sub-command not player only

---

src/main/java/eu/decentsoftware/holograms/api/holograms/Hologram.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java

These two changes fix #144
A potential IndexOutOfBoundsException caused by incorrect index checking is fixed.
Missing page number user input to a 0-indexed array index conversion is fixed.

Fix for #144

---

src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java

Since `owner` (`name`) cannot be null in `GameProfile` on recent versions, the check may set the `owner` instead of the `texture`.

Prioritize texture when parsing item

---

src/main/java/eu/decentsoftware/holograms/plugin/convertors/impl/CMIConverter.java

It seems like CMI now saves the `holograms.yml` file in a `Saves` folder instead of just its plugin folder.
This PR now checks for this file location first and if it is not valid, falls back to the old one for backwards compatability.

Fix file location for CMI converter

---

src/main/java/eu/decentsoftware/holograms/plugin/features/DamageDisplayFeature.java

In my testing, changing this event priority allows more compatibility with some plugins such as AdvancedEnchantments which can modify damage output.

Set damage display event priority to MONITOR

---

src/main/java/eu/decentsoftware/holograms/api/Settings.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java

This PR changes some small stuff for commands and also fixes a wrongly asigned config key.
- Fix `DEFAULT_TEXT` key being `default.text` instead of `defaults.text`
- Add `FACE` to hologram align command syntax.
- Added `FACE` option to line align command for feature compat with hologram variant.
- Change `<range>` to `<interval>` in setupdateinterval hologram command.
- Changed `?` to `help` in page help syntax to keep it the same as all other help command syntaxes.

Improve commands and fix wrong config key

---

src/main/java/eu/decentsoftware/holograms/plugin/features/DamageDisplayFeature.java

There is a mistake where the damage display uses the `mobs` option instead of `zero-damage` when setting the boolean for whether to display values below or equal to 0 damage.

Fix wrong option used for zeroDamage option

---

src/main/java/eu/decentsoftware/holograms/api/commands/CommandBase.java
src/main/java/eu/decentsoftware/holograms/api/commands/CommandInfo.java
src/main/java/eu/decentsoftware/holograms/api/commands/CommandValidator.java
src/main/java/eu/decentsoftware/holograms/api/commands/DecentCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/FeatureSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java
src/main/resources/plugin.yml

Alters the way permissions are checked by allowing a list of permissions to be defined per-command.
If the list is not empty will DH check if the user has `dh.admin` OR any of the defined permissions.
This should allow more fine-grained permission setups.
Also, I updated the plugins.yml too with the new permissions, so that the server and permission plugins know about the permissions.
Permission format is `dh.command.<subcommand>` for the main sub-command and `dh.command.<subcommand>.<arg>` for an argument of a sub-command.
For example, `dh.command.lines.add` grants access to the `/dh lines add ...` sub-command.
This closes #195

Add per-command permissions

---

src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java
src/main/java/eu/decentsoftware/holograms/plugin/DecentHologramsPlugin.java

This fixes the long-standing issue of Item NBT such as `CustomModelData` not working on 1.20.5+ due to the Item Structure having been redone as a whole.
The PR makes use of NBT API, which is shaded into DecentHolograms, do convert the old NBT structure to the new one.
In more detail is it creating an NBT data instance from the ItemStack, applies the NBT provided by the string as `tag` NBT part and then converts it from 1.20.4 Item NBT to the Item NBT used in the server, before converting this final NBT into an ItemStack to return.
This only happens when the Server version is 1.20.5+, with older versions falling back to the currently used method.
Unlike #229 which focuses only on CustomModelData to be fixed, does this fix other NBT data too such as item color and alike (Granted that NBT …

Fix Item NBT not working on 1.20.5+

---

src/main/java/eu/decentsoftware/holograms/api/utils/location/LocationUtils.java

Closes #228 
There seems to be an issue with getting the world when it is in the pattern of `a-b-c-d-e`.
The issue is most likely the `UUID.fromString(value)` method detecting the string as a UUID, returning an instance, even if it was invalid. And given DH only checks if UUID is not null does this result in it trying to return the World from that UUID, which may not work.
This PR changes the logic to first try and get the world by its name. If that fails (world is null) will it try to parse a UUID and get the world through that.
It will also log a failed retrieval if the world is still null after UUID parsing, either due to a failed parsing or because no world was found by the UUID.

Change how DH gets Worlds.

---

src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java

Changes the `fromItemStack(ItemStack)` method to now check for `CustomModelData` or `minecraft:custom_model_data` in an item's `tag` or `components` compount respectively, depending on the version.
This fixes an issue where custom model data is no longer applied to the final String for the HologramItem when used on 1.20.5+, as DH looks for `CustomModelData`.
In addition was the `NBTItem` replaced with `ReadAndWriteNBT` due to the former being deprecated, while also making sure to check in the Item's `tag` or `components` part respectively.
A test jar shared on Discord shows to fix the issue.

Fix `HologramItem.fromItemStack(ItemStack)` not including custom model data.

---

build.gradle
src/main/java/eu/decentsoftware/holograms/api/utils/items/SkullUtils.java
src/main/java/eu/decentsoftware/holograms/api/utils/reflect/ReflectionUtil.java

I've created a fix for the new commit that Spigot has made [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8d52226914ce4b99f35be3d6954f35616d92476d#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java) that changes the CraftMetaSkull class to use a new component ResolveableProfile, that prevented from setting/getting textures due to this change.

Fix resolvable profile error for setting/getting textures.

---

src/main/java/eu/decentsoftware/holograms/api/holograms/Hologram.java

Closes #265 
Updated constructors to require non-null `FileConfig` and added an overloaded constructor with a `saveToFile` parameter. Simplified `delete()` method by removing a null check on the config.

Refactor Hologram constructors to enforce non-null config

---

src/main/java/eu/decentsoftware/holograms/api/holograms/HologramPage.java

Closes #267 
Previously, inserting at the end of the hologram required workarounds as the index check did not permit it. This change updates the logic to allow an index equal to `size()`, enabling straightforward insertion at the end. It improves functionality and aligns with expected behavior.

Allow inserting hologram lines at the end of the list

---

src/main/java/eu/decentsoftware/holograms/api/utils/items/SkullUtils.java
src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java

I've made some improvements towards the `/dh h create` command.
Namely, I've reworked how the plugin detects the `-l:<world>:<x>:<y>:<z>` option by not having it hard-coded in a particular part of the command, but by having it iterate through the args, finding it.
Should it not find it will it simply add the arg to a list to then use as the line content.
I also added a `--center` option, which when present will have the Hologram be centered, as if the `/dh h center` command was used.

Improve -l option detection and add --center option to /dh h create command

---

src/main/java/eu/decentsoftware/holograms/api/holograms/Hologram.java

Essentially made it do what it was supposed to do from the start.
If saveToFile is false, the FileConfig will be null and not initialized.
The reason why this was a problem in the first place was because an inline if statement was being used. Assuming saveToFile was set to faslse, due to java's type checking, this was causing a FileConfig object to be initialized without being used, and as a consequence an empty file would be generated. This is now fixed in this commit.

Refactor saveToFile boolean in Hologram constructor

---

src/main/java/eu/decentsoftware/holograms/api/nms/PacketListener.java

Unnecessary exception suppression for #219 
This exception occurs before a player is disconnected from the server under unspecified conditions.
Nevertheless, it does not affect the plugin's functionality in any way, so I think it is correct to simply hide this exception.
`DefaultChannelPipeline$TailContext#0` is netty handler, so it would be stable on most versions of server software.
Tested on Paper 1.16.5 and Paper 1.21.4. But i was unable to reproduce the NoSuchElementException firing.

Fix NoSuchElementException on packet handler adding

---

src/main/java/eu/decentsoftware/holograms/api/utils/items/HologramItem.java

Mojang broke stuff again... Who would've guessed?
What they broke this time is the custom model data... again.
In 1.21.4, they changed it from `components:{custom_model_data=1}` to `components:{custom_model_data={...}}` where `...` could be any combination of `floats:[<float_list>]`, `flags:[<boolean_list>]`, `strings:[<string_list>]` or `colors:[<float_list|int_list>]`.
This means that our current aproach for parsing an ItemStack by checking the components object for custom_model_data no longer works as it no longer holds the value directly, but instead has it in a floats array.
This PR should fix this issue by checking for `components:{custom_model_data={floats[...]}}` and if present returns the first entry of the list.

Fix Custom Model Data not being found in item... again

---

src/main/java/eu/decentsoftware/holograms/api/Settings.java
src/main/java/eu/decentsoftware/holograms/api/utils/items/ItemBuilder.java
src/main/java/eu/decentsoftware/holograms/api/utils/items/SkullUtils.java
src/main/resources/config.yml

This addresses 2 issues within SkullUtils when fetching A player's UUID or texture:
1. It provides the actual cause when a request fails with an exception.
The order of arguments for the `Log.warn` was wrong, causing the exception to be "swallowed".
To fix this, and to not spam the console with stacktraces, did I add a separate line listing the cause.
2. The timeout has been increased from 50ms to 5 seconds.
Having a timeout of just 50ms is barely anything, as a request seems to take around a second at least, so a timeout of 5 seconds was set here.
I cannot say if there is any performance impact here, but I doubt it to be much.

Fix connection issues within SkullUtils for fetching UUID and texture

---

plugin/src/main/java/eu/decentsoftware/holograms/api/commands/DecentCommand.java
plugin/src/main/java/eu/decentsoftware/holograms/api/commands/DecentCommandException.java
plugin/src/main/java/eu/decentsoftware/holograms/plugin/commands/FeatureSubCommand.java
plugin/src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramSubCommand.java
plugin/src/main/java/eu/decentsoftware/holograms/plugin/commands/HologramsCommand.java
plugin/src/main/java/eu/decentsoftware/holograms/plugin/commands/LineSubCommand.java
plugin/src/main/java/eu/decentsoftware/holograms/plugin/commands/PageSubCommand.java

This is mostly a workaround for the AV false positives we've been getting. It seems the string formatting with `%s` triggered those for some reason.

Printing command help in one place, refactor

---

nms/nms-v1_8_R1/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R1/DataWatcherBuilder.java
nms/nms-v1_8_R1/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R1/EntityPacketsBuilder.java
nms/nms-v1_8_R2/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R2/DataWatcherBuilder.java
nms/nms-v1_8_R2/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R2/EntityPacketsBuilder.java
nms/nms-v1_8_R3/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R3/DataWatcherBuilder.java
nms/nms-v1_8_R3/src/main/java/eu/decentsoftware/holograms/nms/v1_8_R3/EntityPacketsBuilder.java

We should send at least one entity metadata property to the client. Some clients throw an NPE when there are no metadata properties in the Spawn Entity Living packet.

Send at least one property in entity data watcher

---

plugin/src/main/java/eu/decentsoftware/holograms/api/animations/text/WaveAnimation.java

The WaveAnimation can throw an `ArrayIndexOutOfBoundsException` when the provided `<#ANIM>` only contains a single argument.
This PR fixes the issue by having the animation default to white when only one argument is provided.

Fix ArrayIndexOutOfBoundsException for WaveAnimation
